
package com.example.demo.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebserviceDemoService", targetNamespace = "http://webservice.demo.example.com", wsdlLocation = "http://localhost:8500/webservice/webservice?wsdl")
public class WebserviceDemoService_Service
    extends Service
{

    private final static URL WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDEMOSERVICE_EXCEPTION;
    private final static QName WEBSERVICEDEMOSERVICE_QNAME = new QName("http://webservice.demo.example.com", "WebserviceDemoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8500/webservice/webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDEMOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEDEMOSERVICE_EXCEPTION = e;
    }

    public WebserviceDemoService_Service() {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebserviceDemoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebserviceDemoService_Service(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebserviceDemoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebserviceDemoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebserviceDemoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebserviceDemoService
     */
    @WebEndpoint(name = "WebserviceDemoServiceImplPort")
    public WebserviceDemoService getWebserviceDemoServiceImplPort() {
        return super.getPort(new QName("http://webservice.demo.example.com", "WebserviceDemoServiceImplPort"), WebserviceDemoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebserviceDemoService
     */
    @WebEndpoint(name = "WebserviceDemoServiceImplPort")
    public WebserviceDemoService getWebserviceDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.demo.example.com", "WebserviceDemoServiceImplPort"), WebserviceDemoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDEMOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDEMOSERVICE_EXCEPTION;
        }
        return WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    }

}
